pre-release-commit-message = "chore: release v{{version}}"
tag-message = "nightcrow v{{version}}"
push = false
publish = true
pre-release-replacements = [
  { file = "CHANGELOG.md", search = "## Unreleased", replace = "## {{version}} ({{date}})", exactly = 1 },
]
